task: "Extraction"
seed: 2000
batch_size: 16
classifier_lr: 1.e-4
optimizer:
  - params: "model.bert.parameters()"
    lr: ${model_args.lr}
  - params: "model.classifier.parameters()"
    lr: ${model_args.classifier_lr}