model_args: 
  eval_only: False
  data_path: "./Data/fig_dataset.json"
  train_data_path: "./Data/train.json"
  valid_data_path: "./Data/valid.json"
  test_data_path: "./Data/test.json"
  model_name_or_path: "hfl/chinese-roberta-wwm-ext"
  save_dir: "./Checkpoints"
  logs_dir: "./Log"
  arch_name: "bert_seed${model_args.seed}" # architect_name
  lr: 1.e-5
  batch_size: 32
  eval_batch_size: 1
  num_epochs: 20
  num_labels: 13
  task: "Classification" 
  contrast_lambda: 1
  label_pad_id: -1
  seed: 2020
  optimizer: default
  model_init_args: 
    - config
defaults:
  - _self_
  - override hydra/job_logging: custom

hydra:
  job:
    name: "${model_args.logs_dir}/${model_args.task}.${model_args.arch_name}"
  run:
    dir: .
  output_subdir: "${hydra.run.dir}/hydra_outputs/${model_args.task}.${model_args.arch_name}"